version: '3.8'

services:
  frontend:
    image: zhy-ai-chat:latest
    container_name: zhy-ai-chat
    build:
      context: .
    environment:
      TZ: Asia/Shanghai
    ports:
      - "9527:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
#    depends_on:
#      - backend
    restart: unless-stopped
    networks:
      - frp_net

networks:
  frp_net:
    external: true