name: Cleanup Release Assets

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  cleanup:

    runs-on: ubuntu-latest

    env:
      KEEP_RELEASES: 6

    steps:

      - name: Cleanup old release assets

        env:
          GITEA_URL: ${{ gitea.server_url }}
          REPO: ${{ gitea.repository }}
          GITEA_TOKEN: ${{ secrets.PAT_TOKEN }}

        shell: bash

        run: |

          set -e


          echo "Get releases..."


          releases=$(curl -s \
            -H "Authorization: token ${GITEA_TOKEN}" \
            "${GITEA_URL}/api/v1/repos/${REPO}/releases?limit=100")



          echo "$releases" | jq .



          old_release_ids=$(echo "$releases" \
            | jq -r ".[$KEEP_RELEASES:][] | .id")



          if [ -z "$old_release_ids" ]; then

              echo "No old releases"

              exit 0

          fi



          for release_id in $old_release_ids

          do

              echo
              echo "=============================="
              echo "Cleaning release ${release_id}"
              echo "=============================="



              assets=$(curl -s \
                -H "Authorization: token ${GITEA_TOKEN}" \
                "${GITEA_URL}/api/v1/repos/${REPO}/releases/${release_id}/assets")



              echo "$assets" | jq .



              echo "$assets" \
              | jq -r '.[] | "\(.id) \(.name)"' \
              | while read asset_id asset_name


              do

                  echo
                  echo "Delete asset:"
                  echo "release=${release_id}"
                  echo "asset=${asset_id}"
                  echo "name=${asset_name}"



                  result=$(curl \
                    -s \
                    -w "\nHTTP_CODE:%{http_code}" \
                    -X DELETE \
                    -H "Authorization: token ${GITEA_TOKEN}" \
                    "${GITEA_URL}/api/v1/repos/${REPO}/releases/${release_id}/assets/${asset_id}")



                  echo "$result"



                  code=$(echo "$result" \
                    | grep HTTP_CODE \
                    | cut -d: -f2)



                  if [ "$code" = "204" ]

                  then

                      echo "SUCCESS"

                  else

                      echo "FAILED"

                  fi


              done


          done